variables:
  AUDIT_AWS_EC2_ALERT_LIST:
    description: alert list for generating notifications
    required: true
    type: array
    default:
      - ec2-TCP-6379-0.0.0.0/0
      - ec2-ip-address-whitelisted
      - ec2-unrestricted-traffic
      - ec2-TCP-1521-0.0.0.0/0
      - ec2-TCP-3306-0.0.0.0/0
      - ec2-TCP-5432-0.0.0.0/0
      - ec2-TCP-27017-0.0.0.0/0
      - ec2-TCP-1433-0.0.0.0/0
      - ec2-TCP-3389-0.0.0.0/0
      - ec2-TCP-22-0.0.0.0/0
      - ec2-TCP-5439-0.0.0.0/0
      - ec2-TCP-23
      - ec2-TCP-21
      - ec2-TCP-20
      - ec2-ports-range
  AUDIT_AWS_EC2_ALERT_RECIPIENT:
    description: email recipient for notification
    required: true
    type: string
    default:
  AUDIT_AWS_EC2_ALLOW_EMPTY:
    description: receive empty reports?
    required: true
    type: string
    default: false
  AUDIT_AWS_EC2_PAYLOAD_TYPE:
    description: json or text
    required: true
    type: string
    default: "json"
  AUDIT_AWS_EC2_SEND_ON:
    description: always or change
    required: true
    type: string
    default: "change"
  AUDIT_AWS_EC2_REGIONS:
    description: list of AWS regions to check. Default is all regions
    required: true
    type: array
    default:
        - us-east-1
        - us-west-1
        - us-west-2
#       - ap-south-1
#       - ap-northeast-1
#       - ap-northeast-2
#       - ap-southeast-1
#       - ap-southeast-2
#       - eu-central-1
#       - eu-west-1
#       - sa-east-1
